### ISSUE TITLE
Error while configuring using cmake (unable to find boost)

### ISSUE THREAD

**Issue by nelrufus** [pabloariasal/modern-cmake-sample#13]
I get the following error while using Ubuntu 18 and cmake 3.19. Is "boost_headers" a package name or am  I missing something here?

############################################
CMake Error at CMakeLists.txt:10 (find_package):
  Could not find a package configuration file provided by "boost_headers"
  (requested version 1.71) with any of the following names:

    boost_headersConfig.cmake
    boost_headers-config.cmake

  Add the installation prefix of "boost_headers" to CMAKE_PREFIX_PATH or set
  "boost_headers_DIR" to a directory containing one of the above files.  If
  "boost_headers" provides a separate development package or SDK, be sure it
  has been installed.

-- Configuring incomplete, errors occurred!
######################################################

**Comment by maggu2810** [comment]
This solved it for me:

```diff
diff --git a/libjsonutils/CMakeLists.txt b/libjsonutils/CMakeLists.txt
index aabe7fc..eb6d87d 100644
--- a/libjsonutils/CMakeLists.txt
+++ b/libjsonutils/CMakeLists.txt
@@ -6,9 +6,11 @@ list(INSERT CMAKE_MODULE_PATH 0 ${CMAKE_SOURCE_DIR}/cmake)
 
 ##############################################
 # Declare dependencies
-set(MIN_BOOST_VERSION 1.71)
-find_package(boost_headers ${MIN_BOOST_VERSION} REQUIRED CONFIG)
-find_package(boost_regex ${MIN_BOOST_VERSION} REQUIRED CONFIG)
+set(MIN_BOOST_VERSION 1.75)
+find_package(Boost ${MIN_BOOST_VERSION} REQUIRED COMPONENTS
+             regex)
+#find_package(boost_headers ${MIN_BOOST_VERSION} REQUIRED CONFIG)
+#find_package(boost_regex ${MIN_BOOST_VERSION} REQUIRED CONFIG)
 
 set(MIN_RapidJSON_VERSION 1.1)
 find_package(RapidJSON ${MIN_RapidJSON_VERSION} REQUIRED MODULE)
```

**Comment by pabloariasal** [comment]
Thank you both! @maggu2810 jut uploaded the project with your changes.
