### ISSUE TITLE
Incorrect generated include path for rapidjson

### ISSUE THREAD

**Issue by teeks99** [pabloariasal/modern-cmake-sample#2]
When I run this with the CMAKE_PREFIX_PATH=~/tmp/rapidjson (for the git repo), it finds ~/tmp/rapidjson/include/rapidjson as the include directory. However, in json_utils.h it `#include <rapidjson/document.h>`. Because the `rapidjson` is in both the include path and the header file, it fails to find the file.

Is there a way that FindRapidJSON.cmake can include the directory one level up from where rapidjson.h is located?

**Comment by pabloariasal** [comment]
Yes you are right. This directory should be set to `~/tmp/rapidjson/include` in your case. Thank you for finding this.

**Comment by pabloariasal** [comment]
I commited a patch, can you please try again?
