### ISSUE TITLE
Include setup and commands in the readme file

### ISSUE THREAD

**Issue by teeks99** [pabloariasal/modern-cmake-sample#4]
It would be nice if the readme included the necessary commands for beginners to execute the sample.

i.e. - how to get boost, how to build boost (`./bootstrap.sh ; ./b2 --with-regex stage`), how to let cmake find them (`export BOOST_ROOT=/path/to/boost_1_55_0`, `export CMAKE_PREFIX_PATH=/path/to/rapidjson_repo`), where to run cmake from (`cd libjsonutils ; mkdir build; cd build; cmake ..`), etc

**Comment by pabloariasal** [comment]
Yes, will add setup instructions for Linux at least, as I don't have access to a windows or mac.
Normally you wouldn't want to build boost, but just install it using your package manager and let cmake find it for you. Same goes for rapidjson.

**Comment by pabloariasal** [comment]
Build/installation instructions have been added to the README
